#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
   - type: legacy_api_password

frontend:
updater:
  reporting: no
sun:
conversation:
discovery:
  ignore:
    - apple_tv
    - harmony
    - deconz
    - roku
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - REDACTED.0/24
    - REDACTED.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 3

#################################################################
## Components
#################################################################

ecobee:
  api_key: !secret ecobee_api_key

hue:
  bridges:
    - host: REDACTED.106
      allow_hue_groups: false
      allow_unreachable: true

emulated_hue:
  host_ip: REDACTED.105
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

media_player:
  - platform: plex
    entity_namespace: 'plex'
  - platform: yamaha
    name: "Media Center Receiver"
    host: REDACTED.94
    source_ignore:
      - "AUX"
      - "AV1"
      - "AV2"
      - "AV3"
      - "Bluetooth"
      - "Deezer"
      - "MusicCast Link"
      - "NET RADIO"
      - "Pandora"
      - "SERVER"
      - "Spotify"
      - "TIDAL"
      - "TUNER"
      - "USB"
    source_names:
      HDMI1: "Apple TV"
      HDMI2: "Xbox One X"
      HDMI3: "Nintendo Switch"
      HDMI4: "Wii U"
      AUDIO1: "TV Audio"
      AUDIO2: "Sonos Digital"
      AUDIO3: "Sonos"

apple_tv:
  - name: Living Room Apple TV
    host: REDACTED.150
    login_id: !secret apple_tv_login_id
    start_off: false
  - name: Guest Bedroom Apple TV
    host: REDACTED.153
    login_id: !secret apple_tv_login_id
    start_off: false
  - name: Bedroom Apple TV
    host: REDACTED.152
    login_id: !secret apple_tv_login_id
    start_off: false
  - name: USER1's Office Apple TV
    host: REDACTED.151
    login_id: !secret apple_tv_login_id
    start_off: false

remote:
  - platform: harmony
    name: Media Center
    host: REDACTED.109
    activity: Watch TV
  - platform: harmony
    name: Bedroom TV
    host: REDACTED.247
    activity: Watch TV
  - platform: harmony
    name: Office TV
    host: REDACTED.176
    activity: Watch TV

map:

wemo:

switch:
  - platform: tplink
    host: REDACTED.114
    name: MyQ Garage Outlet

ifttt:
  key: !secret ifttt_key

device_tracker:
  - platform: unifi
    username: !secret unifi_username
    password: !secret unifi_password
    host: REDACTED.3
    verify_ssl: false
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  - platform: locative

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

ring:
    username: !secret ring_username
    password: !secret ring_password

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion
  - platform: ping
    host: 8.8.8.8
    name: WAN
    scan_interval: 60
  - platform: ping
    host: REDACTED.1
    name: Gateway
    scan_interval: 60
  - platform: ping
    host: REDACTED.1
    name: Charleston VPN
    scan_interval: 60
  - platform: ping
    host: REDACTED.1
    name: Rochester VPN
    scan_interval: 60

camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://REDACTED.3:7447/REDACTED
    name: Front Porch
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://REDACTED.3:7447/REDACTED
    name: Driveway
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://REDACTED.3:7447/REDACTED
    name: Garage
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://REDACTED.3:7447/REDACTED
    name: Backyard
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://REDACTED.3:7447/REDACTED
    name: Side Yard
#  - platform: ffmpeg
#    input: -rtsp_transport tcp -i rtsp://REDACTED.3:7447/REDACTED
#    name: Living Room
#  - platform: ffmpeg
#    input: -rtsp_transport tcp -i rtsp://REDACTED.3:7447/REDACTED
#    name: Kitchen
  - platform: generic
    still_image_url: https://icons.wxug.com/data/weather-maps/radar/united-states/jefferson-city-missouri-region-current-radar-animation.gif
    name: MO Weather Radar

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key

google:
  client_id: !secret google_client_id
  client_secret: !secret goole_client_secret
  track_new_calendar: true

wink:

vacuum:
  - platform: roomba
    host: REDACTED.228
    username: !secret downstairs_roomba_username
    password: !secret downstairs_roomba_password
    name: Downstairs Roomba
  - platform: roomba
    host: REDACTED.229
    username: !secret upstairs_roomba_username
    password: !secret upstairs_roomba_password
    name: Upstairs Roomba

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: GB
  devices:
    - device_id: !secret dyson_id
      device_ip: REDACTED.95

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
weblink: !include weblinks.yaml
light: !include light_group.yaml
homekit: !include homekit.yaml
ios: !include ios.yaml
