        ##########################################################
        ## House Guest Unlock Doors
        ##########################################################

- alias: Guest - House Guest Unlock Doors

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.house_guest_away
      state: 'on'

  action:
    - service: lock.unlock
      entity_id:
        - lock.back_door
        - lock.front_door

        ##########################################################
        ## After Guest Home Lock Doors
        ########################################################

- alias: Guest - After Guest Home Lock Doors

  trigger:
    - platform: state
      entity_id: input_boolean.house_guest_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: input_boolean.disable_lock_unlock_doors
      state: 'off'
    - condition: state
      entity_id: binary_sensor.front_door_opened
      state: 'off'
    - condition: state
      entity_id: binary_sensor.back_door_opened
      state: 'off'

  action:
    - service: lock.lock
      entity_id:
        - lock.back_door
        - lock.front_door

        ##########################################################
        ## House Guest Home Turn on Lights
        ##########################################################

- alias: Guest - House Guest Turn on Lights

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.house_guest_away
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.kitchen_sink
        - light.living_room_lamps
        - light.dining_room_table
        - light.guest_bedroom_lights
      data:
       color_temp: 447
       brightness_pct: 50
    - service: light.turn_on
      entity_id: light.media_center_lighting
      data:
       transition: 5
       effect: random
       brightness_pct: 75
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
       brightness_pct: 1
    - service: light.turn_on
      entity_id: light.stairs
      data:
       brightness_pct: 50
    - service: light.turn_on
      entity_id: light.hallway_light
      data:
       brightness_pct: 25
    - service: light.turn_on
      entity_id:
        - light.front_porch
        - light.back_door
        - light.garage_light
      data:
       brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
       color_temp: 366
       brightness_pct: 20

        ##########################################################
        ## House Guest Door Code Alarm / Thermostat
        ##########################################################

- alias: Guest - House Guest Door Code Alarm / Thermostat

  trigger:
    - platform: state
      entity_id: group.guest_door_code
      from: 'off'
      to: 'on'

  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.enable_security
        - input_boolean.thermostat_away

        ##########################################################
        ## House Guest Door Code Lights
        ##########################################################

- alias: Guest - House Guest Door Code Lights

  trigger:
    - platform: state
      entity_id: group.guest_door_code
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.house_guest_away
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.kitchen_sink
        - light.living_room_lamps
        - light.dining_room_table
        - light.guest_bedroom_lights
      data:
       color_temp: 447
       brightness_pct: 50
    - service: light.turn_on
      entity_id: light.media_center_lighting
      data:
       transition: 5
       effect: random
       brightness_pct: 75
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
       brightness_pct: 1
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
       brightness_pct: 50
    - service: light.turn_on
      entity_id: light.hallway_light
      data:
       brightness_pct: 25
    - service: light.turn_on
      entity_id:
        - light.front_porch
        - light.back_door
        - light.garage_light
      data:
       brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
       color_temp: 366
       brightness_pct: 20

        ##########################################################
        ## House Guest Home Reset Front Porch Brightness
        ##########################################################

- alias: Guest - House Guest Reset Front Porch Brightness

  trigger:
    - platform: state
      entity_id: input_boolean.house_guest_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.front_porch
      data:
        brightness_pct: 40
        transition: 120

        ##########################################################
        ## House Guest Home Reset Back Door / Garage Brightness
        ##########################################################

- alias: Guest - House Guest Reset Back Door / Garage Brightness

  trigger:
    - platform: state
      entity_id: input_boolean.house_guest_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.back_door
      data:
        brightness_pct: 1
        transition: 120
    - service: light.turn_on
      entity_id: light.garage_light
      data:
       brightness_pct: 1

        ##########################################################
        ## Set House Guest Away after 15 Min
        ##########################################################

- alias: Guest - Set House Guest Away after 15 Mins

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.house_guest_away

        ##########################################################
        ## Set House Guest Home after 10 Mins
        ##########################################################

- alias: Guest - Set House Guest Home after 10 Mins

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.house_guest_away

        ##########################################################
        ## Enable Guest Mode Before Midnight
        ##########################################################

- alias: Guest - Enable Guest Mode Before Midnight

  trigger:
    - platform: time
      at: '23:00'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.overnight_guests
      state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.guest_mode

        ##########################################################
        ## Enable Guest Mode after Midnight
        ##########################################################

- alias: Guest - Enable Guest Mode after Midnight

  trigger:
    - platform: state
      entity_id: group.overnight_guests
      from: 'not_home'
      to: 'home'

  condition:
    - condition: time
      after: '00:00'
      before: '06:00'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.guest_mode

        ##########################################################
        ## Turn off Guest Mode During the Day
        ##########################################################

- alias: Guest - Turn off Guest Mode During the Day

  trigger:
    - platform: time
      at: '10:00'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.guest_mode
