#################################################################
## Lighting Automations
#################################################################

        ##########################################################
        ## Reset Garage Light Brightness when Garage Closed
        ##########################################################

- alias: Lights - Reset Garage Light Brightness when Garage Closed

  trigger:
    - platform: state
      entity_id: cover.garage_door
      from: 'open'
      to: 'closed'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: light.turn_on
      entity_id:
        - light.garage_light
      data:
       brightness_pct: 1

        ##########################################################
        ## Turn on Garage Light when Garage Open
        ##########################################################

- alias: Lights - Turn on Garage Light when Garage Open

  trigger:
    - platform: state
      entity_id: cover.garage_door
      from: 'closed'
      to: 'open'

  condition:
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: light.turn_on
      entity_id:
        - light.garage_light
      data:
       brightness_pct: 100

        ##########################################################
        ## Turn Off Garage Light After 1 Hour
        ##########################################################

- alias: Lights - Turn Off Garage Light After 1 Hour

  trigger:
    - platform: state
      entity_id: light.garage_light
      from: 'off'
      to: 'on'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '04:00'

  action:
    - service: light.turn_off
      entity_id:
        - light.garage_light

        ##########################################################
        ## Turn On Garage Light at Sunset
        ##########################################################

- alias: Lights - Turn On Garage Light at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.garage_light
      data:
       brightness_pct: 1

        ##########################################################
        ## Turn Off Garage Light at Midnight
        ##########################################################

- alias: Lights - Turn Off Garage Light at Midnight

  trigger:
   - platform: time
     at: '23:59'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'

  action:
    - service: light.turn_off
      entity_id:
        - light.garage_light

        ##########################################################
        ## Turn On Front Porch at Sunset
        ##########################################################

- alias: Lights - Turn on Front Porch at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        transition: 900
        brightness_pct: 40
        color_temp: 447

        ##########################################################
        ## Turn Off Front Porch at Midnight
        ##########################################################

- alias: Lights - Turn Off Front Porch at Midnight

  trigger:
   - platform: time
     at: '23:59'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch
      data:
       transition: 300

        ##########################################################
        ## Turn off Front Porch After Midnight
        ##########################################################

- alias: Lights - Turn off Front Porch After Midnight

  trigger:
    - platform: state
      entity_id: light.front_porch
      from: 'off'
      to: 'on'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '05:00'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch
      data:
       transition: 300

        ##########################################################
        ## Turn On Front Yard Outdoor Lighting at Sunset
        ##########################################################

- alias: Lights - Turn On Front Yard Outdoor Lighting at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.front_yard_lighting
    #try again fix
    - delay: '00:00:90'
    - service: switch.turn_on
      entity_id:
        - switch.front_yard_lighting

        ##########################################################
        ## Turn Off Front Yard Outdoor Lighting at 2a
        ##########################################################

- alias: Lights - Turn Off Front Yard Outdoor Lighting at 2a

  trigger:
   - platform: time
     at: '02:00'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.front_yard_lighting
    #try again fix
    - delay: '00:00:90'
    - service: switch.turn_off
      entity_id:
        - switch.front_yard_lighting

        ##########################################################
        ## Turn On Back Door at Sunset
        ##########################################################

- alias: Lights - Turn On Back Door at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
        brightness_pct: 1
        transition: 60

        ##########################################################
        ## Turn On Backyard Deck Lights at Sunset
        ##########################################################

- alias: Lights - Turn On Backyard Deck Lights at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
    - condition: state
      entity_id: group.friends_and_family
      state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.backyard_deck
      data:
        brightness_pct: 1
        transition: 60

        ##########################################################
        ## Turn Off Backyard Deck Lights at Midnight
        ##########################################################

- alias: Lights - Turn Off Backyard Deck Lights at Midnight

  trigger:
   - platform: time
     at: '23:59'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'

  action:
    - service: light.turn_off
      entity_id:
        - light.backyard_deck

        ##########################################################
        ## Turn Off Back Door at Midnight
        ##########################################################

- alias: Lights - Back Door Off at Midnight

  trigger:
    - platform: time
      at: '23:59'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'

  action:
   - service: light.turn_off
     entity_id:
       - light.back_door
     data:
       transition: 300

        ##########################################################
        ## Turn off Back Door After Midnight
        ##########################################################

- alias: Lights - Turn off Back Door After Midnight

  trigger:
    - platform: state
      entity_id: light.back_door
      from: 'off'
      to: 'on'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '04:59'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'

  action:
    - service: light.turn_off
      entity_id:
        - light.back_door

        ##########################################################
        ## Turn on Lights at 5a if USER2 Home and Working
        ##########################################################

- alias: Lights - Turn on Interior Lights at 5a if USER2 Home and Working

  trigger:
    - platform: time
      at: '05:00'

  condition:
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_lights_morning
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_working
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps
        - light.media_center_lighting
      data:
       brightness_pct: 25
       color_temp: 447
    - service: light.turn_on
      entity_id:
        - light.dining_room_table
        - light.kitchen_cabinets
        - light.kitchen_sink
        - light.shower
      data:
       brightness_pct: 1
    - service: light.turn_on
      entity_id:
        - light.bathroom_vanity
      data:
       brightness_pct: 20
    - service: light.turn_on
      entity_id:
        - light.hallway_light
      data:
       brightness_pct: 1
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
       brightness_pct: 1
       transition: 60
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
       color_temp: 366
       brightness_pct: 20

        ##########################################################
        ## Turn off Lights at Sunrise
        ##########################################################

- alias: Lights - Turn off Lights at Sunrise

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '+00:45:00'

  action:
    - service: light.turn_off
      entity_id:
        - group.interior_lights
        - group.exterior_lights
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.front_yard_lighting
    #try again fix
    - delay: '00:00:90'
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.front_yard_lighting

        ##########################################################
        ## Turn On Outdoor Lighting at Sunset
        ##########################################################

- alias: Lights - Turn on Outdoor Lighting at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.backyard_patio_lighting
        - switch.lower_backyard_lighting
    - service: light.turn_on
      entity_id: light.backyard_patio
      data:
        brightness_pct: 1
    #try again fix
    - delay: '00:00:90'
    - service: switch.turn_on
      entity_id:
        - switch.backyard_patio_lighting
        - switch.lower_backyard_lighting

        ##########################################################
        ## Turn Off Outdoor Lighting At 10:00p
        ##########################################################

- alias: Lights - Turn off Outdoor Lighting at 10p

  trigger:
    - platform: time
      at: '22:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
    - service: light.turn_off
      entity_id: light.backyard_patio
    #try again fix
    - delay: '00:00:30'
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting

        ##########################################################
        ## Media Center Lighting Random Color Every Hour
        ##########################################################

- alias: Lights - Media Center Lighting Random Color Every Hour

  trigger:
    - platform: time
      minutes: 0
      seconds: 0

  condition:
    - condition: state
      entity_id: light.media_center_lighting
      state: 'on'
    - condition: state
      entity_id: input_boolean.livingroom_rainbow
      state: 'off'
    - condition: state
      entity_id: input_boolean.interior_holiday
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.media_center_lighting
      data:
        effect: random
        transition: 300

        ##########################################################
        ## Set Globe Color Temp
        ##########################################################

- alias: Lights - Set Globe Color Temp

  trigger:
    - platform: state
      entity_id: light.globe
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 90

  condition:
    - condition: state
      entity_id: input_boolean.livingroom_rainbow
      state: 'off'
    - condition: state
      entity_id: input_boolean.interior_holiday
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_tripped
      state: 'off'
    - condition: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
       color_temp: 366

        ##########################################################
        ## Turn on Guest Bedroom Lamp when Ceiling is on
        ##########################################################

- alias: Lights - Turn on Guest Bedroom Lamp when Ceiling is on

  trigger:
    - platform: state
      entity_id: light.guest_bedroom_ceiling
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: light.guest_bedroom_nightstand
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.guest_bedroom_nightstand
      data:
       brightness: 50

        ##########################################################
        ## Turn off Guest Bedroom Lamp when Ceiling is off
        ##########################################################

- alias: Lights - Turn off Guest Bedroom Lamp when Ceiling is off

  trigger:
    - platform: state
      entity_id: light.guest_bedroom_ceiling
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: light.guest_bedroom_nightstand
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.guest_bedroom_nightstand
      data:
       transition: 3
