#################################################################
## Security Automations
#################################################################

        ##########################################################
        ## Door Alarm
        ##########################################################

- alias: Security - Door Alarm

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.enable_security
      state: 'on'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.alarm_tripped
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       brightness_pct: 100
       color_name: "red"
    - service: light.turn_on
      entity_id:
        - light.hue_lights_exterior
        - light.wink_lights
        - light.wink_exterior
      data:
       brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       flash: long
    - service: wink.enable_siren
      data:
        entity_id: wink.siren
        enabled: 'true'

        ##########################################################
        ## Panic Mode
        ##########################################################

- alias: Security - Panic Mode

  trigger:
    - platform: state
      entity_id: input_boolean.panic_mode
      to: 'on'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.alarm_tripped
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       brightness_pct: 100
       color_name: "red"
    - service: light.turn_on
      entity_id:
        - light.hue_lights_exterior
        - light.wink_lights
        - light.wink_exterior
      data:
       brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       flash: long
    - service: wink.enable_siren
      data:
        entity_id: wink.siren
        enabled: 'true'

        ##########################################################
        ## Shut Off Alarm Manually
        ##########################################################

- alias: Security - Shut Off Alarm Manually

  trigger:
    - platform: state
      entity_id: input_boolean.alarm_tripped
      to: 'off'

  action:
    - service: wink.enable_siren
      data:
        entity_id: wink.siren
        enabled: 'false'

        ##########################################################
        ## Disable Alarm when Home
        ##########################################################

- alias: Security - Disable Alarm when Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.enable_security

        ##########################################################
        ## Enable Alarm when Away
        ##########################################################

- alias: Security - Enable Alarm when Away

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.enable_security
