#################################################################
## Smoke Alarm Automations
#################################################################

        ##########################################################
        ## Smoke Alarm Warning Text Notification
        ##########################################################

- alias: Smoke Alarm - Smoke Alarm Warning Text Notification

  trigger:
    - platform: state
      entity_id: sensor.living_room_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 1
    - platform: state
      entity_id: sensor.bedroom_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 1
    - platform: state
      entity_id: sensor.kitchen_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 1
    - platform: state
      entity_id: sensor.hallway_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 1
    - platform: state
      entity_id: sensor.upstairs_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 1
    - platform: state
      entity_id: sensor.basement_nest_protect_smoke_status
      to: 'Warning'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Warning Smoke Alarm Might Sound!
        data:
          push:
            badge: 0
            category: "smokealarm"

        ##########################################################
        ## Smoke Alarm Text Notification
        ##########################################################

- alias: Smoke Alarm - Smoke Alarm Text Notification

  trigger:
    - platform: state
      entity_id: sensor.living_room_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.bedroom_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.kitchen_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
#    - platform: state
#      entity_id: sensor.hallway_nest_protect_smoke_status
#      to: 'Emergency'
#      for:
#        hours: 0
#        minutes: 0
#        seconds: 15
    - platform: state
      entity_id: sensor.upstairs_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.basement_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: input_boolean.disable_fire_alarm
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Smoke Alarm!
        data:
          push:
            category: camera
          entity_id: camera.driveway

        ##########################################################
        ## Smoke Alarm Turn on Lights
        ##########################################################

- alias: Smoke Alarm - Smoke Alarm Turn on Lights

  trigger:
    - platform: state
      entity_id: sensor.living_room_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.bedroom_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.kitchen_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
#    - platform: state
#      entity_id: sensor.hallway_nest_protect_smoke_status
#      to: 'Emergency'
#      for:
#        hours: 0
#        minutes: 0
#        seconds: 15
    - platform: state
      entity_id: sensor.upstairs_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.basement_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_fire_alarm
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       brightness_pct: 100
       color_name: "red"
    - service: light.turn_on
      entity_id:
        - light.wink_lights
      data:
       brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       flash: long

        ##########################################################
        ## Smoke Alarm Audio Notification
        ##########################################################

- alias: Smoke Alarm - Smoke Audio Alarm

  trigger:
    - platform: state
      entity_id: sensor.living_room_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.bedroom_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.kitchen_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
#    - platform: state
#      entity_id: sensor.hallway_nest_protect_smoke_status
#      to: 'Emergency'
#      for:
#        hours: 0
#        minutes: 0
#        seconds: 15
    - platform: state
      entity_id: sensor.upstairs_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.basement_nest_protect_smoke_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_fire_alarm
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '1'
          what: 'Smoke Has Been Detected!'

        ##########################################################
        ## CO Alarm Text Notification
        ##########################################################

- alias: Smoke Alarm - CO Alarm Text Notification

  trigger:
    - platform: state
      entity_id: sensor.living_room_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.bedroom_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.kitchen_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.hallway_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.upstairs_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.basement_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3

  condition:
    - condition: state
      entity_id: input_boolean.disable_fire_alarm
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Carbon Monoxide Alarm!
        data:
          push:
            category: camera
          entity_id: camera.driveway
    - service: notify.ios_USER2s_iphone
      data:
        message: Carbon Monoxide Alarm!
        data:
          push:
            category: camera
          entity_id: camera.driveway

        ##########################################################
        ## CO Alarm Turn on Lights
        ##########################################################

- alias: Smoke Alarm - CO Alarm Turn on Lights

  trigger:
    - platform: state
      entity_id: sensor.living_room_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.bedroom_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.kitchen_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.hallway_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.upstairs_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.basement_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_fire_alarm
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       brightness_pct: 100
       color_name: "red"
    - service: light.turn_on
      entity_id:
        - light.wink_lights
      data:
       brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       flash: long

        ##########################################################
        ## CO Alarm Audio Notification
        ##########################################################

- alias: Smoke Alarm - CO Audio Alarm

  trigger:
    - platform: state
      entity_id: sensor.living_room_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.bedroom_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.kitchen_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.hallway_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.upstairs_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id: sensor.basement_nest_protect_co_status
      to: 'Emergency'
      for:
        hours: 0
        minutes: 0
        seconds: 3

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_fire_alarm
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '1'
          what: 'Carbon monoxide Has Been Detected!'

        ##########################################################
        ## Reset Disable Fire Alarm
        ##########################################################

- alias: Smoke Alarm - Reset Disable Fire Alarm

  trigger:
    - platform: state
      entity_id: input_boolean.disable_smoke_alarm
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.disable_smoke_alarm
